# Generated by Django 5.2.5 on 2025-11-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0002_categoria_producto_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
